# Generated by Django 3.2.9 on 2021-12-18 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='班级名称')),
                ('amount', models.PositiveIntegerField(default=0, verbose_name='课程容量')),
                ('attends', models.PositiveIntegerField(default=0, verbose_name='上课人数')),
                ('grade_type', models.CharField(choices=[('PF', '二级制'), ('SC', '百分制'), ('13', '十三级制')], default='SC', max_length=2, verbose_name='打分制')),
            ],
        ),
        migrations.CreateModel(
            name='StudentCourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(null=True, verbose_name='成绩')),
                ('grade_type', models.CharField(choices=[('PF', '二级制'), ('SC', '百分制'), ('13', '十三级制')], default='SC', max_length=2, verbose_name='打分制')),
                ('courseClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.class', verbose_name='课程班级')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.IntegerField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WEN'), (4, 'THU'), (5, 'FRI'), (6, 'SAT'), (7, 'SUN')], verbose_name='星期')),
                ('start_time', models.TimeField(verbose_name='上课时间')),
                ('end_time', models.TimeField(verbose_name='下课时间')),
                ('location', models.CharField(max_length=100, verbose_name='上课地点')),
                ('week_interval', models.IntegerField(choices=[(0, '每周'), (1, '单周'), (2, '双周')], default=1, verbose_name='周间隔')),
                ('courseClass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.class', verbose_name='课程')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=32, verbose_name='院系名称')),
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='院系编号')),
                ('dept_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='院系对应操作用户')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='课程编码')),
                ('name', models.CharField(max_length=50, verbose_name='课程名')),
                ('description', models.CharField(max_length=250, null=True, verbose_name='课程描述')),
                ('credit', models.IntegerField(verbose_name='学分')),
                ('dept', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.department', verbose_name='开课院系')),
                ('requirements', models.ManyToManyField(to='course.Course', verbose_name='先修课程')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程'),
        ),
        migrations.AddField(
            model_name='class',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mgmt.semester', verbose_name='学期'),
        ),
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='教师'),
        ),
    ]
