# Generated by Django 3.2.9 on 2021-12-06 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_teacher_info'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mgmt', '0001_initial'),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='max_number',
        ),
        migrations.RemoveField(
            model_name='course',
            name='semester',
        ),
        migrations.RemoveField(
            model_name='course',
            name='status',
        ),
        migrations.RemoveField(
            model_name='course',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='course',
            name='year',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='course',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='end_week',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='schedule',
            name='start_week',
        ),
        migrations.AlterField(
            model_name='course',
            name='id',
            field=models.CharField(max_length=6, primary_key=True, serialize=False, verbose_name='课程编码'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='week_interval',
            field=models.IntegerField(choices=[(0, '每周'), (1, '单周'), (2, '双周')], default=1, verbose_name='周间隔'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='weekday',
            field=models.IntegerField(choices=[(1, 'MON'), (2, 'TUE'), (3, 'WEN'), (4, 'THU'), (5, 'FRI'), (6, 'SAT'), (7, 'SUN')], verbose_name='星期？'),
        ),
        migrations.AlterField(
            model_name='studentcourse',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='StudentCourseInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.PositiveIntegerField(null=True, verbose_name='成绩')),
                ('course', models.ManyToManyField(to='course.Course', verbose_name='课程')),
                ('semester', models.ManyToManyField(to='mgmt.Semester', verbose_name='学期')),
                ('student', models.ManyToManyField(to='user.Student', verbose_name='学生')),
            ],
        ),
        migrations.CreateModel(
            name='OpenCourseApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('N', '待审核'), ('P', '通过'), ('F', '不通过')], default='N', max_length=1, verbose_name='审核状态')),
                ('course', models.ManyToManyField(to='course.Course', verbose_name='课程')),
                ('teacher', models.ManyToManyField(to='user.Teacher', verbose_name='教师')),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('dept_name', models.CharField(max_length=32, verbose_name='院系名称')),
                ('dept_no', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='院系编号')),
                ('dept_user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='院系对应操作用户')),
            ],
        ),
        migrations.CreateModel(
            name='CourseSelectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_remain', models.PositiveSmallIntegerField(default=0, verbose_name='剩余名额')),
                ('course', models.ManyToManyField(to='course.Course', verbose_name='课程')),
                ('semester', models.ManyToManyField(to='mgmt.Semester', verbose_name='学期')),
            ],
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course', verbose_name='课程')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.schedule', verbose_name='上课时间')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.teacher', verbose_name='教师')),
            ],
        ),
    ]
