# Generated by Django 3.2.9 on 2021-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester_name', models.CharField(max_length=20, null=True, verbose_name='学期名称')),
                ('semester_year', models.PositiveSmallIntegerField(null=True, verbose_name='学年')),
                ('semester_no', models.PositiveSmallIntegerField(null=True, verbose_name='学期编号')),
                ('start_time', models.DateField(verbose_name='学期开始日期')),
                ('end_time', models.DateField(verbose_name='学期结束日期')),
                ('select_start', models.DateTimeField(verbose_name='选课开始时间')),
                ('select_end', models.DateTimeField(verbose_name='选课结束时间')),
            ],
        ),
    ]
