# Generated by Django 3.2.9 on 2021-12-16 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mgmt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='semester_no',
            field=models.CharField(max_length=10, null=True, verbose_name='学期编号'),
        ),
        migrations.AlterField(
            model_name='semester',
            name='semester_year',
            field=models.PositiveIntegerField(null=True, verbose_name='学年'),
        ),
    ]
