# Generated by Django 3.2.8 on 2021-11-08 11:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('dept', '院系'), ('admin', '系统管理员')], max_length=7, verbose_name='角色')),
                ('need_complete_info', models.BooleanField(default=True, verbose_name='是否需要更新个人信息')),
                ('name', models.CharField(max_length=50, null=True, verbose_name='用户名')),
                ('is_active', models.BooleanField(default=True, verbose_name='用户状态')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否为管理员')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('number', models.CharField(max_length=6, verbose_name='班级学号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('department_no', models.CharField(max_length=3, verbose_name='院系号')),
                ('info', models.CharField(help_text='不要超过250字', max_length=255, verbose_name='教师简介')),
            ],
        ),
    ]
