# Generated by Django 3.2.8 on 2021-10-23 07:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('uid', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=32, verbose_name='邮箱')),
                ('role', models.CharField(choices=[('student', '学生'), ('teacher', '教师'), ('dept', '院系'), ('admin', '系统管理员')], max_length=7, verbose_name='角色')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('number', models.CharField(max_length=6, verbose_name='班级学号')),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], max_length=1, verbose_name='性别')),
                ('birthday', models.DateField(null=True, verbose_name='生日')),
                ('info', models.CharField(help_text='不要超过250字', max_length=255, verbose_name='教师简介')),
                ('department_no', models.CharField(max_length=3, verbose_name='院系号')),
            ],
        ),
    ]
