# Generated by Django 3.2.9 on 2021-12-06 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='info',
            field=models.CharField(help_text='不要超过250字', max_length=255, null=True, verbose_name='教师简介'),
        ),
    ]
