# Generated by Django 3.2.8 on 2021-10-26 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20211025_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='need_complete_info',
            field=models.BooleanField(default=True, verbose_name='是否需要更新个人信息'),
        ),
    ]
